
package sample.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sample-soap", targetNamespace = "http://com.sample")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SampleSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(action = "getInt")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://com.sample", className = "sample.com.GetInt")
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://com.sample", className = "sample.com.GetIntResponse")
    public int getInt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
