/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.appoptics.ext.thriftgenerated;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum HostType implements org.apache.thrift.TEnum {
  PERSISTENT(1),
  AWS_LAMBDA(2);

  private final int value;

  private HostType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static HostType findByValue(int value) { 
    switch (value) {
      case 1:
        return PERSISTENT;
      case 2:
        return AWS_LAMBDA;
      default:
        return null;
    }
  }
}
