/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.appoptics.ext.thriftgenerated;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum OboeSettingType implements org.apache.thrift.TEnum {
  DEFAULT_SAMPLE_RATE(2),
  LAYER_SAMPLE_RATE(3),
  LAYER_APP_SAMPLE_RATE(4),
  LAYER_HTTPHOST_SAMPLE_RATE(5),
  CONFIG_STRING(6),
  CONFIG_INT(7);

  private final int value;

  private OboeSettingType(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static OboeSettingType findByValue(int value) { 
    switch (value) {
      case 2:
        return DEFAULT_SAMPLE_RATE;
      case 3:
        return LAYER_SAMPLE_RATE;
      case 4:
        return LAYER_APP_SAMPLE_RATE;
      case 5:
        return LAYER_HTTPHOST_SAMPLE_RATE;
      case 6:
        return CONFIG_STRING;
      case 7:
        return CONFIG_INT;
      default:
        return null;
    }
  }
}
