/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
package com.appoptics.ext.thriftgenerated;


import java.util.Map;
import java.util.HashMap;
import org.apache.thrift.TEnum;

public enum ResultCode implements org.apache.thrift.TEnum {
  OK(0),
  TRY_LATER(1),
  INVALID_API_KEY(2),
  LIMIT_EXCEEDED(3),
  REDIRECT(4);

  private final int value;

  private ResultCode(int value) {
    this.value = value;
  }

  /**
   * Get the integer value of this enum value, as defined in the Thrift IDL.
   */
  public int getValue() {
    return value;
  }

  /**
   * Find a the enum type by its integer value, as defined in the Thrift IDL.
   * @return null if the value is not found.
   */
  public static ResultCode findByValue(int value) { 
    switch (value) {
      case 0:
        return OK;
      case 1:
        return TRY_LATER;
      case 2:
        return INVALID_API_KEY;
      case 3:
        return LIMIT_EXCEEDED;
      case 4:
        return REDIRECT;
      default:
        return null;
    }
  }
}
