
package sample.com;

import java.util.concurrent.Future;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.AsyncHandler;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.Response;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sample-soap", targetNamespace = "http://com.sample")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SampleSoap {


    /**
     * 
     * @param arg0
     * @return
     *     returns javax.xml.ws.Response<sample.com.GetIntResponse>
     */
    @WebMethod(operationName = "getInt", action = "getInt")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://com.sample", className = "sample.com.GetInt")
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://com.sample", className = "sample.com.GetIntResponse")
    public Response<GetIntResponse> getIntAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

    /**
     * 
     * @param arg0
     * @param asyncHandler
     * @return
     *     returns java.util.concurrent.Future<? extends java.lang.Object>
     */
    @WebMethod(operationName = "getInt", action = "getInt")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://com.sample", className = "sample.com.GetInt")
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://com.sample", className = "sample.com.GetIntResponse")
    public Future<?> getIntAsync(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0,
        @WebParam(name = "asyncHandler", targetNamespace = "")
        AsyncHandler<GetIntResponse> asyncHandler);

    /**
     * 
     * @param arg0
     * @return
     *     returns int
     */
    @WebMethod(action = "getInt")
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://com.sample", className = "sample.com.GetInt")
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://com.sample", className = "sample.com.GetIntResponse")
    @Action(input = "getInt", output = "http://com.sample/sample-soap/getIntResponse")
    public int getInt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0);

}
