
/*
 * 
 */

package sample.com;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.2.1
 * Fri May 31 11:15:13 PDT 2013
 * Generated source version: 2.2.1
 * 
 */


@WebServiceClient(name = "OperatorService", 
                  wsdlLocation = "http://localhost:8888/ws/server?wsdl",
                  targetNamespace = "http://com.sample") 
public class OperatorService extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://com.sample", "OperatorService");
    public final static QName SampleSoapPort = new QName("http://com.sample", "sample-soapPort");
    static {
        URL url = null;
        try {
            url = new URL("http://localhost:8888/ws/server?wsdl");
        } catch (MalformedURLException e) {
            System.err.println("Can not initialize the default wsdl from http://localhost:8888/ws/server?wsdl");
            // e.printStackTrace();
        }
        WSDL_LOCATION = url;
    }

    public OperatorService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public OperatorService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public OperatorService() {
        super(WSDL_LOCATION, SERVICE);
    }

    /**
     * 
     * @return
     *     returns SampleSoap
     */
    @WebEndpoint(name = "sample-soapPort")
    public SampleSoap getSampleSoapPort() {
        return super.getPort(SampleSoapPort, SampleSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns SampleSoap
     */
    @WebEndpoint(name = "sample-soapPort")
    public SampleSoap getSampleSoapPort(WebServiceFeature... features) {
        return super.getPort(SampleSoapPort, SampleSoap.class, features);
    }

}
