package sample.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.2.1
 * Fri May 31 11:15:13 PDT 2013
 * Generated source version: 2.2.1
 * 
 */
 
@WebService(targetNamespace = "http://com.sample", name = "sample-soap")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleSoap {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://com.sample", className = "sample.com.GetInt")
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://com.sample", className = "sample.com.GetIntResponse")
    @WebMethod(action = "getInt")
    public int getInt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
