package sample.com;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-05-06T16:46:34.921-07:00
 * Generated source version: 2.7.3
 * 
 */
@WebService(targetNamespace = "http://com.sample", name = "sample-soap")
@XmlSeeAlso({ObjectFactory.class})
public interface SampleSoap {

    @WebResult(name = "return", targetNamespace = "")
    @RequestWrapper(localName = "getInt", targetNamespace = "http://com.sample", className = "sample.com.GetInt")
    @WebMethod
    @ResponseWrapper(localName = "getIntResponse", targetNamespace = "http://com.sample", className = "sample.com.GetIntResponse")
    public int getInt(
        @WebParam(name = "arg0", targetNamespace = "")
        int arg0
    );
}
