apiVersion: v1
kind: Service
metadata:
  name: tomcat-agent
  labels:
    app: tomcat-agent
    tier: backend
spec:
  #type: NodePort
  type: LoadBalancer
  ports:
    # the port that this service should serve on
  - port: 8080
  selector:
    app: tomcat-agent
    tier: backend
