
package com.ebay.marketplace.search.v1.services;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.jws.soap.SOAPBinding;
import javax.xml.bind.annotation.XmlSeeAlso;

/**
 * This class was generated by Apache CXF 2.7.3
 * 2013-04-30T17:19:56.432-07:00
 * Generated source version: 2.7.3
 * 
 */
public final class FindingServicePortType_FindingServiceSOAPPort_Client {

    private static final QName SERVICE_NAME = new QName("http://www.ebay.com/marketplace/search/v1/services", "FindingService");

    private FindingServicePortType_FindingServiceSOAPPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = FindingService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) { 
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }
      
        FindingService ss = new FindingService(wsdlURL, SERVICE_NAME);
        FindingServicePortType port = ss.getFindingServiceSOAPPort();  
        
        {
        System.out.println("Invoking findItemsByProduct...");
        com.ebay.marketplace.search.v1.services.FindItemsByProductRequest _findItemsByProduct_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsByProductResponse _findItemsByProduct__return = port.findItemsByProduct(_findItemsByProduct_messageParameters);
        System.out.println("findItemsByProduct.result=" + _findItemsByProduct__return);


        }
        {
        System.out.println("Invoking getSearchKeywordsRecommendation...");
        com.ebay.marketplace.search.v1.services.GetSearchKeywordsRecommendationRequest _getSearchKeywordsRecommendation_messageParameters = null;
        com.ebay.marketplace.search.v1.services.GetSearchKeywordsRecommendationResponse _getSearchKeywordsRecommendation__return = port.getSearchKeywordsRecommendation(_getSearchKeywordsRecommendation_messageParameters);
        System.out.println("getSearchKeywordsRecommendation.result=" + _getSearchKeywordsRecommendation__return);


        }
        {
        System.out.println("Invoking getHistograms...");
        com.ebay.marketplace.search.v1.services.GetHistogramsRequest _getHistograms_messageParameters = null;
        com.ebay.marketplace.search.v1.services.GetHistogramsResponse _getHistograms__return = port.getHistograms(_getHistograms_messageParameters);
        System.out.println("getHistograms.result=" + _getHistograms__return);


        }
        {
        System.out.println("Invoking findItemsIneBayStores...");
        com.ebay.marketplace.search.v1.services.FindItemsIneBayStoresRequest _findItemsIneBayStores_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsIneBayStoresResponse _findItemsIneBayStores__return = port.findItemsIneBayStores(_findItemsIneBayStores_messageParameters);
        System.out.println("findItemsIneBayStores.result=" + _findItemsIneBayStores__return);


        }
        {
        System.out.println("Invoking findItemsByImage...");
        com.ebay.marketplace.search.v1.services.FindItemsByImageRequest _findItemsByImage_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsByImageResponse _findItemsByImage__return = port.findItemsByImage(_findItemsByImage_messageParameters);
        System.out.println("findItemsByImage.result=" + _findItemsByImage__return);


        }
        {
        System.out.println("Invoking findItemsByCategory...");
        com.ebay.marketplace.search.v1.services.FindItemsByCategoryRequest _findItemsByCategory_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsByCategoryResponse _findItemsByCategory__return = port.findItemsByCategory(_findItemsByCategory_messageParameters);
        System.out.println("findItemsByCategory.result=" + _findItemsByCategory__return);


        }
        {
        System.out.println("Invoking findCompletedItems...");
        com.ebay.marketplace.search.v1.services.FindCompletedItemsRequest _findCompletedItems_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindCompletedItemsResponse _findCompletedItems__return = port.findCompletedItems(_findCompletedItems_messageParameters);
        System.out.println("findCompletedItems.result=" + _findCompletedItems__return);


        }
        {
        System.out.println("Invoking findItemsForFavoriteSearch...");
        com.ebay.marketplace.search.v1.services.FindItemsForFavoriteSearchRequest _findItemsForFavoriteSearch_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsForFavoriteSearchResponse _findItemsForFavoriteSearch__return = port.findItemsForFavoriteSearch(_findItemsForFavoriteSearch_messageParameters);
        System.out.println("findItemsForFavoriteSearch.result=" + _findItemsForFavoriteSearch__return);


        }
        {
        System.out.println("Invoking getVersion...");
        com.ebay.marketplace.search.v1.services.GetVersionRequest _getVersion_messageParameters = null;
        com.ebay.marketplace.search.v1.services.GetVersionResponse _getVersion__return = port.getVersion(_getVersion_messageParameters);
        System.out.println("getVersion.result=" + _getVersion__return);


        }
        {
        System.out.println("Invoking findItemsAdvanced...");
        com.ebay.marketplace.search.v1.services.FindItemsAdvancedRequest _findItemsAdvanced_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsAdvancedResponse _findItemsAdvanced__return = port.findItemsAdvanced(_findItemsAdvanced_messageParameters);
        System.out.println("findItemsAdvanced.result=" + _findItemsAdvanced__return);


        }
        {
        System.out.println("Invoking findItemsByKeywords...");
        com.ebay.marketplace.search.v1.services.FindItemsByKeywordsRequest _findItemsByKeywords_messageParameters = null;
        com.ebay.marketplace.search.v1.services.FindItemsByKeywordsResponse _findItemsByKeywords__return = port.findItemsByKeywords(_findItemsByKeywords_messageParameters);
        System.out.println("findItemsByKeywords.result=" + _findItemsByKeywords__return);


        }

        System.exit(0);
    }

}
