name: Core libs with Maven

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: branch, tag or SHA to checkout. defaults to ref or SHA of triggering event.

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        ref: ${{ github.event.inputs.checkout-ref }}
    - name: Set up JDK 8
      id: setup-jdk-8
      uses: actions/setup-java@v1
      with:
        java-version: 8.0.112
    - name: Set up JDK 11
      id: setup-jdk-11
      uses: actions/setup-java@v1
      with:
        java-version: 11.0.10
    - name: Build with Maven
      run: |
        git rev-parse HEAD > commit
        mvn -B package --file pom.xml
      env:
          JAVA_1_8_HOME : "${{ steps.setup-jdk-8.outputs.path }}"
          JAVA_HOME : "${{ steps.setup-jdk-11.outputs.path }}"
    - name: Publish package
      run: mvn --batch-mode deploy
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

