name: Core libs with Maven

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: branch, tag or SHA to checkout. defaults to ref or SHA of triggering event.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

