name: Core libs with Maven

on:
  workflow_dispatch:
    inputs:
      checkout-ref:
        description: branch, tag or SHA to checkout. defaults to ref or SHA of triggering event.

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 8
        id: setup-jdk-8
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.112
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Publish package
        run: mvn --batch-mode deploy -DskipTests
        env:
          JAVA_1_8_HOME: "${{ steps.setup-jdk-8.outputs.path }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

