name: Core libs with Maven

on:
  workflow_dispatch:
    push:
      tags:
        - "v*.*.*"
    inputs:
      checkout-ref:
        description: branch, tag or SHA to checkout. defaults to ref or SHA of triggering event.
      release-name:
        description: the release name

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.checkout-ref }}
      - name: Set up JDK 8
        id: setup-jdk-8
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.112
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Set version env to pom version
        run: |
          echo "POM_VERSION=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          JAVA_1_8_HOME: "${{ steps.setup-jdk-8.outputs.path }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release and upload artifacts
        run: gh release create ${{ env.RELEASE_NAME || env.POM_VERSION }} --title "${{ env.RELEASE_NAME || env.POM_VERSION }}" core/target/core-*.jar dependencies/target/dependencies-*.jar metrics/target/metrics-*.jar
        env:
          RELEASE_NAME: v${{ github.event.inputs.release-name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}


