name: Core libs with Maven

on:
  workflow_dispatch:
    push:
      tags:
        - "v*.*.*"
    inputs:
      checkout-ref:
        description: branch, tag or SHA to checkout. defaults to ref or SHA of triggering event.

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: ${{ github.event.inputs.checkout-ref }}
      - name: Set up JDK 8
        id: setup-jdk-8
        uses: actions/setup-java@v1
        with:
          java-version: 8.0.112
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: "Build Changelog"
        id: github_release
        uses: mikepenz/release-changelog-builder-action@v2.8.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish package
        run: mvn --batch-mode deploy
        env:
          JAVA_1_8_HOME: "${{ steps.setup-jdk-8.outputs.path }}"
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Release and upload artifacts
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          body: "${{steps.github_release.outputs.changelog}}"
          files: |
            core/target/core-*.jar
            dependencies/target/dependencies-*.jar
            metrics/target/metrics-*.jar

