name: Release

on:
  workflow_dispatch:

permissions:
  packages: write
  contents: write
  id-token: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8.0.302
          distribution: 'temurin'

      - name: Set version env to pom version
        run: |
          echo "POM_VERSION=v$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV

      - name: Publish package
        run: |
          VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)
          NEW_VERSION=${VERSION%%-SNAPSHOT}
          
          mvn versions:set -DnewVersion=$NEW_VERSION
          mvn -s .github/m2/settings.xml -Dmaven.resolver.transport=wagon --batch-mode deploy
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}